language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - DJANGO_VERSION="1.4"
  - DJANGO_VERSION="1.5"
  - DJANGO_VERSION="1.6"
  - DJANGO_VERSION="1.7"

install:
  - pip install "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
  - pip install -r requirements.txt

script: python manage.py test drip

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION="1.3"
    - python: "3.4"
      env: DJANGO_VERSION="1.3"
    - python: "3.3"
      env: DJANGO_VERSION="1.4"
    - python: "3.4"
      env: DJANGO_VERSION="1.4"
